name: Docker

on:
  push:
  pull_request:
  schedule:
    - cron: '17 3 * * *'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: Docker Login
        id: docker-login
        if: success() && github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      - name: Docker Build and Push
        if: steps.docker-login.outcome == 'success'
        run: ./build.sh "--push"
      - name: Docker Build
        if: steps.docker-login.outcome == 'skipped'
        run: ./build.sh
      - name: Docker Clear
        if: always() && steps.docker-login.outcome == 'success'
        run: |
          rm -f ${HOME}/.docker/config.json
